import type { VigilanceRule } from "./vigilance";

/**
 * Les vigilances issues de la Base maître « Connecteur Pharma » V1.
 *
 * Cent règles écrites par le pharmacien associé (classeur des 16 et 17
 * septembre 2026), chacune avec son déclencheur, sa famille, son mécanisme, sa
 * source primaire et son niveau : conseil, dépistage, surveillance,
 * interaction, blocage. Ici, elles deviennent des règles du moteur — une par
 * FAMILLE de médicaments plutôt qu'une par ligne du classeur, parce qu'au
 * comptoir un patient sous AVK doit lire UNE carte qui dit tout, pas huit.
 *
 * Correspondance avec le classeur : chaque règle porte `sourceRules`, les
 * numéros des lignes qu'elle couvre. Un test vérifie que les cent lignes sont
 * couvertes, ou explicitement écartées avec une raison
 * (`src/core/ai/engines/base-maitre.ts`).
 *
 * Ce que le niveau du classeur devient dans le moteur :
 *   🔴 BLOCAGE      → `blockTags` : la référence n'est jamais proposée ;
 *   🔴 INTERACTION  → `cautionTags` + `precautionText` : proposée avec la
 *                     consigne d'espacement sur la carte ;
 *   🟠 SURVEILLANCE → MONITORING, `cautionTags` ;
 *   🟡 DÉPISTAGE    → SCREENING, sans proposition automatique ;
 *   🟢 CONSEIL      → règle de conseil (`advice.ts`), pas ici.
 *
 * Les formulations restent prudentes (« peut », jamais « doit ») et chaque
 * règle cite la source primaire du classeur. Les règles marquées « À valider »
 * dans le classeur le restent : le statut est dans `docs/base-maitre-v1.md`.
 */

const ODS = (sheet: string) => `NIH Office of Dietary Supplements — ${sheet} (Health Professional fact sheet)`;
const NCCIH = (sheet: string) => `NCCIH (NIH) — ${sheet}`;
const ANSM_THESAURUS = "Thésaurus des interactions médicamenteuses, ANSM";

export const BASE_MAITRE_VIGILANCES: VigilanceRule[] = [
  // ------------------------------------------------------------ Antithrombotiques
  {
    key: "antiplatelet-bleeding-supplements",
    version: "1.0",
    kind: "MONITORING",
    severity: "WARNING",
    title: "Surveillance",
    subtitle: "Antiagrégant plaquettaire détecté",
    atcPrefixes: ["B01AC"],
    substances: ["clopidogrel", "prasugrel", "ticagrelor", "acide acetylsalicylique", "kardegic", "aspirine"],
    explanationTemplate:
      "Sous antiagrégant ({drug}), plusieurs compléments peuvent majorer le risque de saignement : l'ail concentré, le ginkgo, le ginseng, la vitamine E à forte dose (au-delà d'environ 400 UI par jour). Ils ne se proposent pas d'eux-mêmes ; en cas d'ecchymoses ou de saignements inhabituels, ou avant une chirurgie, on les arrête.",
    concerned: ["Ail concentré (compléments, pas l'usage alimentaire)", "Ginkgo biloba", "Ginseng asiatique", "Vitamine E à forte dose"],
    patientAdvice: "Signalez toute prise de complément à base d'ail, de ginkgo ou de ginseng, et tout saignement inhabituel.",
    blockTags: [],
    cautionTags: ["ail", "ginkgo", "ginseng", "vitamine e"],
    precautionText: "Antiagrégant sur l'ordonnance : risque de saignement majoré, à ne proposer qu'après avis et en surveillant.",
    sources: [NCCIH("Garlic"), NCCIH("Ginkgo"), NCCIH("Asian Ginseng"), ODS("Vitamin E")],
    sourceRules: [62, 64, 90],
  },

  // ------------------------------------------------------------ Antidiabétiques
  {
    key: "antidiabetic-glycemia-supplements",
    version: "1.0",
    kind: "MONITORING",
    severity: "WARNING",
    title: "Surveillance",
    subtitle: "Antidiabétique détecté",
    atcPrefixes: ["A10"],
    substances: ["insuline", "gliclazide", "glimepiride", "repaglinide", "sitagliptine", "empagliflozine", "dapagliflozine", "semaglutide", "liraglutide"],
    explanationTemplate:
      "Avec un antidiabétique ({drug}), certains compléments peuvent modifier la glycémie : le chrome et le ginseng asiatique peuvent l'abaisser (hypoglycémie), la niacine à dose pharmacologique peut l'augmenter, la coenzyme Q10 peut interférer avec l'insuline. Aucun ne se propose sans plan d'autosurveillance et sans l'avis du prescripteur.",
    concerned: ["Chrome", "Ginseng asiatique", "Niacine (vitamine B3) à forte dose", "Coenzyme Q10 (sous insuline)"],
    patientAdvice: "Avant tout complément à base de chrome, de ginseng ou de niacine, parlez-en à votre médecin et surveillez vos glycémies.",
    blockTags: [],
    cautionTags: ["chrome", "ginseng", "niacine", "coenzyme q10"],
    precautionText: "Antidiabétique sur l'ordonnance : effet possible sur la glycémie, autosurveillance et avis médical avant de proposer.",
    sources: [ODS("Chromium"), NCCIH("Asian Ginseng"), ODS("Niacin"), NCCIH("Coenzyme Q10")],
    sourceRules: [69, 73, 74, 76, 89],
  },

  // ------------------------------------------------------------ Corticoïdes systémiques
  {
    key: "systemic-corticosteroid-bone-licorice",
    version: "1.0",
    kind: "SCREENING",
    severity: "INFO",
    title: "Dépistage / vigilance",
    subtitle: "Corticoïde systémique détecté",
    atcPrefixes: ["H02AB"],
    substances: ["prednisone", "prednisolone", "methylprednisolone", "dexamethasone", "betamethasone", "hydrocortisone"],
    explanationTemplate:
      "Une corticothérapie systémique prolongée ({drug}) altère le métabolisme de la vitamine D et l'absorption du calcium, et expose l'os. Au long cours, la prévention osseuse (vitamine D, calcium, apports) s'évalue avec le prescripteur, à dose individualisée. La réglisse contenant de la glycyrrhizine se déconseille : hypertension, hypokaliémie, troubles du rythme.",
    concerned: ["Vitamine D et calcium : prévention osseuse à évaluer si traitement prolongé", "Réglisse (glycyrrhizine) : à éviter"],
    patientAdvice: "Si le traitement dure, demandez à votre médecin si une prévention osseuse est utile ; évitez la réglisse.",
    blockTags: [],
    cautionTags: ["réglisse"],
    precautionText: "Corticoïde sur l'ordonnance : la réglisse (glycyrrhizine) majore hypertension et perte de potassium.",
    sources: [ODS("Vitamin D"), NCCIH("Licorice Root")],
    sourceRules: [20, 21, 82],
  },

  // ------------------------------------------------------------ Antiépileptiques
  {
    key: "antiepileptic-nutrition-and-inducers",
    version: "1.0",
    kind: "MONITORING",
    severity: "WARNING",
    title: "Surveillance",
    subtitle: "Antiépileptique détecté",
    atcPrefixes: ["N03A"],
    substances: ["carbamazepine", "phenytoine", "phenobarbital", "primidone", "valproate", "valproique", "lamotrigine", "levetiracetam", "oxcarbazepine", "topiramate"],
    explanationTemplate:
      "Au long cours, les antiépileptiques ({drug}) — surtout carbamazépine, phénytoïne, phénobarbital, primidone et valproate — sont associés à un risque osseux (vitamine D), à une baisse des folates, de la vitamine B6 et de la biotine. Rien ne se supplémente d'office : les folates et la vitamine B6 à forte dose peuvent à leur tour modifier les concentrations du traitement. Le millepertuis diminue l'effet de plusieurs antiépileptiques : il est écarté.",
    concerned: ["Millepertuis (écarté)", "Vitamine D / santé osseuse : à évaluer si traitement prolongé", "Folates : supplémentation à coordonner (interaction dans les deux sens)", "Vitamine B6 : pas de forte dose sans avis", "Biotine : bilan avant conseil, fausse plusieurs analyses"],
    patientAdvice: "Ne prenez pas de millepertuis. Tout complément en folates, vitamine B6 ou vitamine D se décide avec votre neurologue.",
    blockTags: ["millepertuis"],
    cautionTags: ["acide folique", "vitamine b6", "vitamine d", "biotine"],
    precautionText: "Antiépileptique sur l'ordonnance : supplémentation à coordonner avec le prescripteur, pas de conseil autonome.",
    sources: ["MHRA Drug Safety Update — Antiepileptics: adverse effects on bone", ODS("Folate"), ODS("Vitamin B6"), ODS("Biotin"), NCCIH("St. John's Wort")],
    sourceRules: [22, 23, 24, 25, 26, 33, 34, 35, 56, 78, 92],
  },
  {
    key: "gabapentin-antacid-spacing",
    version: "1.0",
    kind: "INTERACTION",
    severity: "WARNING",
    title: "Interaction potentielle",
    subtitle: "Gabapentine détectée",
    atcPrefixes: ["N03AX12"],
    substances: ["gabapentine"],
    explanationTemplate:
      "Les antiacides à base d'aluminium ou de magnésium diminuent la biodisponibilité de la gabapentine ({drug}), d'environ 20 % selon l'information produit. La gabapentine se prend au moins 2 heures après l'antiacide.",
    concerned: ["Antiacides aluminium / magnésium"],
    patientAdvice: "Prenez la gabapentine au moins 2 heures après un antiacide.",
    blockTags: [],
    cautionTags: ["antiacide"],
    precautionText: "Gabapentine sur l'ordonnance : antiacide au moins 2 heures avant la gabapentine.",
    sources: ["FDA — Neurontin (gabapentin) prescribing information, 2017"],
    sourceRules: [94],
  },

  // ------------------------------------------------------------ Absorption : IPP, séquestrants, orlistat
  {
    key: "ppi-longterm-b12-iron",
    version: "1.0",
    kind: "SCREENING",
    severity: "INFO",
    title: "Dépistage / vigilance",
    subtitle: "IPP détecté",
    atcPrefixes: ["A02BC"],
    substances: ["omeprazole", "esomeprazole", "pantoprazole", "lansoprazole", "rabeprazole"],
    explanationTemplate:
      "Un IPP au long cours ({drug}) peut diminuer l'absorption de la vitamine B12 alimentaire et du fer non héminique. Chez un patient âgé, dénutri, ou fatigué avec fourmillements, un dosage se discute avec le médecin avant toute supplémentation : on ne masque pas une carence. Un traitement par fer déjà en cours peut être moins efficace.",
    concerned: ["Vitamine B12 : dosage avant conseil si facteurs de risque", "Fer : absorption réduite, carence documentée à signaler"],
    patientAdvice: null,
    blockTags: [],
    cautionTags: ["fer"],
    precautionText: "IPP sur l'ordonnance : absorption du fer réduite par la baisse d'acidité, efficacité à surveiller.",
    sources: [ODS("Vitamin B12"), ODS("Iron")],
    sourceRules: [8, 9],
  },
  {
    key: "bile-acid-sequestrant-vitamins",
    version: "1.0",
    kind: "INTERACTION",
    severity: "WARNING",
    title: "Interaction potentielle",
    subtitle: "Séquestrant des acides biliaires détecté",
    atcPrefixes: ["C10AC"],
    substances: ["colestyramine", "cholestyramine", "colestipol", "colesevelam"],
    explanationTemplate:
      "{drug} réduit l'absorption des vitamines liposolubles A, D, E et K, et de nombreux médicaments. Tout complément vitaminique se prend à distance (1 heure avant ou 4 heures après). Sous AVK, la vitamine K devient un point de vigilance majeur.",
    concerned: ["Vitamines A, D, E, K et multivitamines : à distance", "Vitamine K sous AVK : vigilance majeure"],
    patientAdvice: "Prenez vos vitamines 1 heure avant ou 4 heures après ce médicament.",
    blockTags: [],
    cautionTags: ["vitamine a", "vitamine d", "vitamine e", "vitamine k", "multivitamines"],
    precautionText: "Séquestrant sur l'ordonnance : 1 heure avant ou 4 heures après, jamais en même temps.",
    sources: [ODS("Vitamin K")],
    sourceRules: [28, 29],
  },

  // ------------------------------------------------------------ Folates
  {
    key: "methotrexate-folate-protocol",
    version: "1.0",
    kind: "MONITORING",
    severity: "WARNING",
    title: "Surveillance",
    subtitle: "Méthotrexate détecté",
    atcPrefixes: ["L01BA01", "L04AX03"],
    substances: ["methotrexate"],
    explanationTemplate:
      "Le méthotrexate ({drug}) est un antagoniste des folates. À faible dose hebdomadaire (rhumatologie, dermatologie), l'acide folique prescrit un autre jour de la semaine réduit certains effets indésirables : vérifier qu'il figure sur l'ordonnance, sans en improviser la dose. En oncologie, les folates peuvent interférer avec l'effet du traitement : aucun conseil autonome, tout passe par le protocole.",
    concerned: ["Acide folique : uniquement selon le protocole prescrit, jamais en conseil autonome"],
    patientAdvice: "Ne prenez d'acide folique ou de folates que selon la prescription qui accompagne votre méthotrexate.",
    blockTags: ["acide folique"],
    cautionTags: [],
    precautionText: null,
    sources: [ODS("Folate")],
    sourceRules: [31, 32],
  },
  {
    key: "sulfasalazine-folate",
    version: "1.0",
    kind: "SCREENING",
    severity: "INFO",
    title: "Dépistage / vigilance",
    subtitle: "Sulfasalazine détectée",
    atcPrefixes: ["A07EC01"],
    substances: ["sulfasalazine"],
    explanationTemplate:
      "La sulfasalazine ({drug}) inhibe l'absorption intestinale des folates. Au long cours, et particulièrement en cas de grossesse ou de projet de grossesse, le statut en folates se discute avec le prescripteur, qui fixe la dose.",
    concerned: ["Folates (vitamine B9) : statut à évaluer, dose à valider"],
    patientAdvice: null,
    blockTags: [],
    cautionTags: ["acide folique"],
    precautionText: "Sulfasalazine sur l'ordonnance : dose de folates à faire valider par le prescripteur.",
    sources: [ODS("Folate")],
    sourceRules: [30],
  },

  // ------------------------------------------------------------ Interactions d'espacement
  {
    key: "levodopa-iron-spacing",
    version: "1.0",
    kind: "INTERACTION",
    severity: "WARNING",
    title: "Interaction potentielle",
    subtitle: "Lévodopa détectée",
    atcPrefixes: ["N04BA"],
    substances: ["levodopa"],
    explanationTemplate:
      "Le fer peut réduire l'absorption de la lévodopa ({drug}) et donc son effet. Un complément en fer se prend à distance, jamais en même temps.",
    concerned: ["Fer"],
    patientAdvice: "Ne prenez pas votre fer en même temps que la lévodopa : espacez les prises.",
    blockTags: [],
    cautionTags: ["fer"],
    precautionText: "Lévodopa sur l'ordonnance : le fer se prend à distance.",
    sources: [ODS("Iron")],
    sourceRules: [38],
  },
  {
    key: "antiretroviral-cations-and-inducers",
    version: "1.0",
    kind: "INTERACTION",
    severity: "WARNING",
    title: "Interaction potentielle",
    subtitle: "Antirétroviral détecté",
    atcPrefixes: ["J05AJ", "J05AR", "J05AE", "J05AF", "J05AG", "J05AX"],
    substances: ["dolutegravir", "bictegravir", "raltegravir", "elvitegravir", "cabotegravir"],
    explanationTemplate:
      "Les compléments en calcium, fer ou magnésium chélatent les inhibiteurs d'intégrase comme le dolutégravir ({drug}) et réduisent leur absorption : à jeun, l'antirétroviral se prend 2 heures avant ou 6 heures après ; au cours d'un repas, calcium et fer peuvent être pris ensemble selon le RCP. Le millepertuis diminue fortement l'exposition de nombreux antirétroviraux : il est écarté sans exception.",
    concerned: ["Millepertuis (écarté)", "Calcium, fer, magnésium : espacement selon le RCP"],
    patientAdvice: "Aucun millepertuis. Vos compléments minéraux se prennent à distance de votre traitement, comme indiqué sur la notice.",
    blockTags: ["millepertuis"],
    cautionTags: ["calcium", "fer", "magnésium"],
    precautionText: "Antirétroviral sur l'ordonnance : à jeun, 2 heures avant ou 6 heures après le traitement.",
    sources: ["Song et al., 2015 — dolutegravir and polyvalent cations (PubMed 25449994)", ODS("Calcium"), NCCIH("St. John's Wort")],
    sourceRules: [44, 57, 96],
  },
  {
    key: "penicillamine-zinc-spacing",
    version: "1.0",
    kind: "INTERACTION",
    severity: "WARNING",
    title: "Interaction potentielle",
    subtitle: "Pénicillamine détectée",
    atcPrefixes: ["M01CC01"],
    substances: ["penicillamine"],
    explanationTemplate:
      "Le zinc réduit l'absorption et l'action de la pénicillamine ({drug}). Les prises s'espacent d'au moins 1 heure.",
    concerned: ["Zinc"],
    patientAdvice: "Espacez le zinc et la pénicillamine d'au moins 1 heure.",
    blockTags: [],
    cautionTags: ["zinc"],
    precautionText: "Pénicillamine sur l'ordonnance : au moins 1 heure d'écart.",
    sources: [ODS("Zinc")],
    sourceRules: [50],
  },
  {
    key: "green-tea-extract-interactions",
    version: "1.0",
    kind: "INTERACTION",
    severity: "WARNING",
    title: "Interaction potentielle",
    subtitle: "Traitement sensible aux extraits de thé vert",
    atcPrefixes: ["C07AA12", "G03XC01", "C10AA05"],
    substances: ["nadolol", "raloxifene", "atorvastatine"],
    explanationTemplate:
      "Les extraits concentrés de thé vert (gélules, comprimés — pas la boisson habituelle) peuvent réduire l'exposition de {drug} : baisse de l'effet du nadolol, de l'atorvastatine, interaction observée avec le raloxifène. Ils ne se proposent pas ; si le patient en prend déjà, le prescripteur en est informé.",
    concerned: ["Extraits de thé vert (compléments)"],
    patientAdvice: "Évitez les compléments à base d'extrait de thé vert ; le thé en boisson n'est pas concerné.",
    blockTags: [],
    cautionTags: ["thé vert"],
    precautionText: "Traitement sensible au thé vert sur l'ordonnance : extrait concentré à éviter.",
    sources: [NCCIH("Green Tea")],
    sourceRules: [83, 84, 85],
  },

  // ------------------------------------------------------------ Blocages
  {
    key: "statin-red-yeast-rice",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Statine détectée",
    atcPrefixes: ["C10AA", "C10BA", "C10BX"],
    substances: ["atorvastatine", "simvastatine", "rosuvastatine", "pravastatine", "fluvastatine"],
    explanationTemplate:
      "La levure de riz rouge apporte de la monacoline K, identique à la lovastatine : cumulée à une statine ({drug}), elle additionne les risques musculaire, hépatique et rénal. Elle est écartée. La coenzyme Q10 n'a pas fait la preuve d'une efficacité régulière sur les douleurs musculaires sous statine : des myalgies, une faiblesse ou des urines foncées appellent un avis médical, pas un complément. Avec la simvastatine, le millepertuis peut diminuer l'effet hypolipémiant.",
    concerned: ["Levure de riz rouge (écartée)", "Coenzyme Q10 : pas de solution validée aux myalgies", "Millepertuis (simvastatine)", "Cocktail antioxydant (simvastatine + niacine)"],
    patientAdvice: "Pas de levure de riz rouge avec une statine. Des douleurs musculaires inhabituelles se signalent au médecin.",
    blockTags: ["levure de riz rouge"],
    cautionTags: ["coenzyme q10", "millepertuis", "antioxydant"],
    precautionText: "Statine sur l'ordonnance : myalgies = avis médical ; efficacité de la CoQ10 non établie.",
    sources: [NCCIH("Red Yeast Rice"), NCCIH("Coenzyme Q10"), NCCIH("St. John's Wort"), ODS("Vitamin E")],
    sourceRules: [59, 67, 70, 71],
  },
  {
    key: "hormonal-contraception-millepertuis",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Contraception hormonale détectée",
    atcPrefixes: ["G03A", "G02BA03", "G02BB"],
    substances: ["ethinylestradiol", "levonorgestrel", "desogestrel", "drospirenone", "dienogest", "nomegestrol"],
    explanationTemplate:
      "Le millepertuis induit les enzymes et transporteurs qui éliminent les hormones : avec une contraception hormonale ({drug}), il expose à un échec contraceptif. Il est écarté ; si la patiente en prend déjà, une méthode additionnelle se discute avec le prescripteur.",
    concerned: ["Millepertuis (écarté)"],
    patientAdvice: "Ne prenez pas de millepertuis avec votre contraception.",
    blockTags: ["millepertuis"],
    cautionTags: [],
    precautionText: null,
    sources: [NCCIH("St. John's Wort"), `${ANSM_THESAURUS} — millepertuis et contraceptifs hormonaux : association contre-indiquée`],
    sourceRules: [51],
  },
  {
    key: "immunosuppressant-supplements",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Immunosuppresseur détecté",
    atcPrefixes: ["L04AD", "L04AA06", "L04AA10", "L04AA18"],
    substances: ["ciclosporine", "tacrolimus", "mycophenolate", "sirolimus", "everolimus"],
    explanationTemplate:
      "Avec un immunosuppresseur ({drug}), le millepertuis peut réduire fortement l'exposition du traitement (risque de rejet ou de perte d'efficacité) et l'échinacée pourrait s'opposer à l'immunosuppression : les deux sont écartés. Les antiacides à base d'aluminium ou de magnésium réduisent l'absorption du mycophénolate : jamais en même temps, l'antiacide 2 heures après.",
    concerned: ["Millepertuis (écarté)", "Échinacée (écartée)", "Antiacides aluminium / magnésium : 2 heures après le mycophénolate"],
    patientAdvice: "Aucun millepertuis ni échinacée. Tout complément se valide avec votre équipe de greffe ou votre spécialiste.",
    blockTags: ["millepertuis", "échinacée"],
    cautionTags: ["antiacide"],
    precautionText: "Immunosuppresseur sur l'ordonnance : antiacide 2 heures après le mycophénolate, jamais en même temps.",
    sources: [NCCIH("St. John's Wort"), NCCIH("Echinacea"), "Mayo Clinic — mycophenolate mofetil (oral route), interactions"],
    sourceRules: [52, 88, 95],
  },
  {
    key: "cardiac-narrow-margin-millepertuis",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Traitement cardiaque à marge étroite détecté",
    atcPrefixes: ["C01AA05", "C01EB17"],
    substances: ["digoxine", "ivabradine"],
    explanationTemplate:
      "Le millepertuis peut diminuer les concentrations et l'efficacité de {drug}, avec une perte d'effet potentiellement grave. Il est écarté ; si le patient en prend, le prescripteur vérifie le traitement.",
    concerned: ["Millepertuis (écarté)"],
    patientAdvice: "Ne prenez pas de millepertuis avec ce traitement.",
    blockTags: ["millepertuis"],
    cautionTags: [],
    precautionText: null,
    sources: [NCCIH("St. John's Wort"), `${ANSM_THESAURUS} — millepertuis et digoxine, ivabradine`],
    sourceRules: [54],
  },
  {
    key: "serotonergic-antidepressant-millepertuis",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Antidépresseur sérotoninergique détecté",
    atcPrefixes: ["N06AA", "N06AB", "N06AF", "N06AG", "N06AX"],
    substances: ["sertraline", "escitalopram", "citalopram", "fluoxetine", "paroxetine", "venlafaxine", "duloxetine", "amitriptyline", "clomipramine", "mirtazapine", "vortioxetine"],
    explanationTemplate:
      "Le millepertuis additionne ses effets sérotoninergiques à ceux de {drug} : risque de syndrome sérotoninergique. Il est écarté. Si le patient en prend déjà, rechercher agitation, tremblements, diarrhée, fièvre.",
    concerned: ["Millepertuis (écarté)"],
    patientAdvice: "Ne prenez jamais de millepertuis avec votre antidépresseur.",
    blockTags: ["millepertuis"],
    cautionTags: [],
    precautionText: null,
    sources: [NCCIH("St. John's Wort"), `${ANSM_THESAURUS} — millepertuis et antidépresseurs sérotoninergiques`],
    sourceRules: [55],
  },
  {
    key: "anticancer-supplements",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Traitement anticancéreux détecté",
    atcPrefixes: ["L01"],
    substances: ["irinotecan", "imatinib", "docetaxel", "paclitaxel", "capecitabine", "tamoxifene"],
    explanationTemplate:
      "Pendant un traitement anticancéreux ({drug}), aucun complément ne se conseille de façon autonome : le millepertuis peut réduire l'exposition de plusieurs anticancéreux, et les antioxydants à forte dose (vitamine E, vitamine C, bêta-carotène, sélénium) pourraient modifier l'effet de traitements qui reposent sur les dommages oxydatifs. Tout passe par l'accord de l'équipe d'oncologie.",
    concerned: ["Millepertuis (écarté)", "Vitamine E, vitamine C et cocktails antioxydants à forte dose (écartés sans accord oncologique)"],
    patientAdvice: "Aucun complément sans l'accord de votre oncologue.",
    blockTags: ["millepertuis", "vitamine e", "vitamine c", "antioxydant"],
    cautionTags: ["multivitamines"],
    precautionText: "Traitement anticancéreux sur l'ordonnance : accord de l'oncologue avant tout complément.",
    sources: [NCCIH("St. John's Wort"), ODS("Vitamin E"), ODS("Vitamin C")],
    sourceRules: [58, 65, 66],
  },
  {
    key: "antithyroid-iodine",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Antithyroïdien détecté",
    atcPrefixes: ["H03B"],
    substances: ["carbimazole", "thiamazole", "methimazole", "propylthiouracile", "benzylthiouracile"],
    explanationTemplate:
      "De fortes doses d'iode (compléments iodés, algues, kelp, fucus) s'ajoutent à l'effet de {drug} et exposent à une hypothyroïdie ou à un déséquilibre. Les compléments iodés sont écartés sans validation endocrinologique.",
    concerned: ["Iode, kelp, fucus, algues (écartés)"],
    patientAdvice: "Évitez les compléments contenant de l'iode ou des algues.",
    blockTags: ["iode"],
    cautionTags: [],
    precautionText: null,
    sources: [ODS("Iodine")],
    sourceRules: [79],
  },
  {
    key: "sedative-kava",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Sédatif détecté",
    atcPrefixes: ["N05BA", "N05CD", "N05CF"],
    substances: ["alprazolam", "bromazepam", "diazepam", "lorazepam", "oxazepam", "zolpidem", "zopiclone"],
    explanationTemplate:
      "Le kava additionne ses effets sédatifs à ceux de {drug} (somnolence, altération psychomotrice, risque de chute) et porte son propre risque hépatique. Il est écarté.",
    concerned: ["Kava (écarté)"],
    patientAdvice: "Pas de kava avec ce traitement.",
    blockTags: ["kava"],
    cautionTags: [],
    precautionText: null,
    sources: [NCCIH("Kava")],
    sourceRules: [86],
  },
  {
    key: "hepatotoxic-drug-supplements",
    version: "1.0",
    kind: "MONITORING",
    severity: "WARNING",
    title: "Surveillance",
    subtitle: "Médicament à risque hépatique connu détecté",
    atcPrefixes: ["J04A", "D01BA02", "C01BD01", "L04AX03", "N03AG01"],
    substances: ["isoniazide", "rifampicine", "pyrazinamide", "terbinafine", "amiodarone", "methotrexate", "valproate", "valproique"],
    explanationTemplate:
      "{drug} porte un risque hépatique connu. On ne lui ajoute pas un second : le kava, les extraits concentrés de thé vert et certaines formulations de curcumine à biodisponibilité augmentée (avec pipérine) ont été associés à des atteintes hépatiques. Ils sont écartés ou vérifiés ; fatigue marquée, urines foncées ou jaunisse imposent d'arrêter et d'orienter.",
    concerned: ["Kava (écarté)", "Extraits concentrés de thé vert", "Curcuma / curcumine à biodisponibilité augmentée"],
    patientAdvice: "Évitez les compléments à base de kava, d'extrait de thé vert ou de curcumine concentrée ; signalez fatigue inhabituelle, urines foncées ou jaunisse.",
    blockTags: ["kava"],
    cautionTags: ["thé vert", "curcuma"],
    precautionText: "Médicament hépatotoxique sur l'ordonnance : cumul de risque hépatique, à éviter.",
    sources: [NCCIH("Kava"), NCCIH("Green Tea"), NCCIH("Turmeric")],
    sourceRules: [87, 99, 100],
  },
  {
    key: "acitretin-vitamin-a",
    version: "1.0",
    kind: "CONTRAINDICATION",
    severity: "WARNING",
    title: "Contre-indication / vigilance",
    subtitle: "Rétinoïde systémique détecté",
    atcPrefixes: ["D05BB02", "D11AH04"],
    substances: ["acitretine", "alitretinoine"],
    explanationTemplate:
      "Avec un rétinoïde systémique ({drug}), un apport en vitamine A s'ajoute au traitement et expose à une hypervitaminose A. Les compléments riches en vitamine A, et les multivitamines qui en contiennent, sont écartés sans validation ; la composition se vérifie.",
    concerned: ["Vitamine A et multivitamines qui en contiennent (écartées)"],
    patientAdvice: "Évitez tout complément contenant de la vitamine A pendant le traitement.",
    blockTags: ["vitamine a"],
    cautionTags: ["multivitamines"],
    precautionText: "Rétinoïde sur l'ordonnance : vérifier l'absence de vitamine A dans la composition.",
    sources: [ODS("Vitamin A")],
    sourceRules: [47],
  },
  {
    key: "lithium-calcium",
    version: "1.0",
    kind: "MONITORING",
    severity: "WARNING",
    title: "Surveillance",
    subtitle: "Lithium détecté",
    atcPrefixes: ["N05AN01"],
    substances: ["lithium"],
    explanationTemplate:
      "Le lithium ({drug}) peut favoriser une hypercalcémie ; un apport en calcium ou en vitamine D peut en augmenter le risque. Une supplémentation se discute au vu de la calcémie, avec le prescripteur.",
    concerned: ["Calcium", "Vitamine D"],
    patientAdvice: null,
    blockTags: [],
    cautionTags: ["calcium", "vitamine d"],
    precautionText: "Lithium sur l'ordonnance : calcémie à vérifier avant tout apport en calcium ou vitamine D.",
    sources: [ODS("Calcium")],
    sourceRules: [48],
  },

  // ------------------------------------------------------------ Dépistages et bon usage
  {
    key: "theophylline-b6",
    version: "1.0",
    kind: "SCREENING",
    severity: "INFO",
    title: "Dépistage / vigilance",
    subtitle: "Théophylline détectée",
    atcPrefixes: ["R03DA04"],
    substances: ["theophylline"],
    explanationTemplate:
      "Un traitement chronique par théophylline ({drug}) est associé à de faibles concentrations de vitamine B6. Des symptômes neurologiques compatibles justifient un bilan avec le médecin, pas une supplémentation automatique.",
    concerned: ["Vitamine B6 : bilan avant conseil"],
    patientAdvice: null,
    blockTags: [],
    cautionTags: ["vitamine b6"],
    precautionText: "Théophylline sur l'ordonnance : pas de supplémentation en B6 sans bilan.",
    sources: [ODS("Vitamin B6")],
    sourceRules: [93],
  },
  {
    key: "usage-cycloserine-b6",
    version: "1.0",
    kind: "USAGE",
    severity: "INFO",
    title: "Bon usage",
    subtitle: "Cyclosérine",
    atcPrefixes: ["J04AB01"],
    substances: ["cycloserine"],
    explanationTemplate:
      "La cyclosérine ({drug}) augmente les pertes urinaires de vitamine B6 et sa neurotoxicité. La prévention par vitamine B6 relève du protocole médical : vérifier qu'elle est prescrite, sans en improviser la dose.",
    concerned: ["Vitamine B6 : selon prescription"],
    patientAdvice: "Prenez la vitamine B6 exactement comme elle vous a été prescrite avec la cyclosérine.",
    blockTags: [],
    cautionTags: ["vitamine b6"],
    precautionText: "Cyclosérine sur l'ordonnance : la vitamine B6 suit la prescription, pas un conseil de comptoir.",
    sources: [ODS("Vitamin B6")],
    sourceRules: [91],
  },
];
