import type { Metadata } from "next";
import { PUBLIC_CONTACT_EMAIL } from "@/config/contact";

export const metadata: Metadata = { title: "Confidentialité et données" };

export default function PrivacyPage() {
  const email = PUBLIC_CONTACT_EMAIL;
  const blocks: { t: string; p: string[]; id?: string }[] = [
    { t: "Sur ce site", p: ["Les formulaires de démonstration et d'abonnement collectent le nom de l'officine, le nom du contact, un e-mail, un téléphone et une ville. Ces données servent uniquement à vous répondre et à préparer votre espace. Elles ne sont ni revendues ni partagées.", `Le formulaire « Devenir partenaire » collecte la société, la marque, le nom, la fonction et les coordonnées du contact, et les informations données sur l'offre du laboratoire. Elles servent uniquement à étudier la candidature et à recontacter la marque ; une candidature non retenue est supprimée sur simple demande à ${email}.`, "Ce site ne dépose aucun traceur publicitaire."] },
    { id: "candidatures-commerciales", t: "Les candidatures commerciales", p: ["Le formulaire « Devenir commercial » collecte votre prénom, votre nom, votre e-mail, votre téléphone, votre ville ou secteur, votre situation actuelle, la zone où vous souhaitez travailler, la description de votre expérience et de votre motivation. Si vous le joignez, votre CV (un fichier PDF) est aussi conservé : c'est facultatif. Aucune donnée de santé n'est demandée.", `Ces informations servent uniquement à étudier votre candidature et à vous recontacter. Elles ne sont ni revendues ni partagées. Un e-mail d'accusé de réception est envoyé à l'adresse indiquée. Votre candidature et votre CV ne sont consultables que par l'équipe PharmaBoost, après connexion à sa console. Pour les faire supprimer, il suffit d'écrire à ${email} : la suppression se fait sur simple demande.`] },
    { t: "Dans l'application", p: ["PharmaBoost traite, pour le compte de l'officine, des données de délivrance et, lorsque le pharmacien les saisit, des données patient. L'officine est responsable de traitement ; PharmaBoost agit comme sous-traitant, dans le cadre d'un contrat écrit.", "Les données sont isolées par officine, chiffrées en transit et au repos, hébergées chez Vercel (application) et Neon (base de données). Chaque accès et chaque décision de conseil sont journalisés."] },
    { t: "Ce que l'intelligence artificielle voit", p: ["Le modèle lit le texte d'une ordonnance pour en extraire les lignes et classer les médicaments. Il ne reçoit ni le nom du patient, ni le stock, ni les prix. Il ne nomme jamais un produit et ne rédige aucun conseil : les règles de conseil et les vigilances sont écrites et relues par des pharmaciens.", "Un e-mail envoyé à un patient ne contient aucune donnée de santé : seul un lien protégé mène à son plan."] },
    { t: "Les nouveautés de votre pharmacie", p: ["Quand votre pharmacie vous envoie votre plan par e-mail, le message peut vous proposer, en option, d'être prévenu(e) lorsqu'une nouvelle gamme arrive en pharmacie. C'est facultatif : votre plan n'en dépend pas. Vous vous abonnez vous-même, depuis le lien de l'e-mail : tant que vous n'avez pas ouvert ce lien et confirmé, votre adresse n'est enregistrée nulle part.", "Si vous acceptez, votre adresse e-mail est conservée, chiffrée, 36 mois au plus à compter de votre accord, puis supprimée. Nous ne conservons aucune donnée de santé, ni votre nom : cette adresse n'est reliée ni à votre ordonnance, ni à votre plan, ni à un médicament. Elle n'est transmise à aucun laboratoire.", "Vous vous désinscrivez à tout moment, en un clic et sans compte, depuis le lien présent dans chaque message : votre adresse est alors effacée.", "Le responsable de ce traitement est votre pharmacie : c'est elle qui décide de ce qu'elle vous écrit, au plus un message par semaine. PharmaBoost n'intervient que comme prestataire technique, pour l'hébergement et l'envoi des messages. Pour exercer vos droits d'accès, de rectification ou de suppression, adressez-vous à votre pharmacie."] },
    { t: "Les messages de PharmaBoost aux professionnels", p: ["PharmaBoost écrit aussi à des professionnels : titulaires d'officines, laboratoires et sociétés partenaires. Ces messages présentent nos offres, le parrainage entre officines ou l'invitation à présenter une gamme. Ils ne s'adressent jamais à des patients.", "Chaque message commercial contient, en pied de page, un lien pour ne plus recevoir nos offres : un clic suffit, sans compte, et nous ne gardons alors qu'une empreinte illisible de votre adresse, pour respecter votre choix. Une invitation envoyée individuellement à un laboratoire vous demande plutôt de répondre au message pour ne plus être sollicité. Les messages liés à un contrat ou à un abonnement en cours (facturation, signature, sécurité du compte) continuent de vous parvenir.", `Nous conservons l'historique de ces envois (adresse professionnelle, nom, date et résultat de l'envoi) pour savoir qui a reçu quoi et pour respecter les désinscriptions ; la durée de cette conservation est en cours de définition et sera précisée ici. PharmaBoost est responsable de ces messages : pour exercer vos droits, écrivez à ${email}.`] },
    { t: "Vos droits", p: [`Accès, rectification, effacement, opposition : écrivez à ${email}. Pour les données traitées dans l'application, adressez-vous d'abord à votre pharmacie, responsable de traitement.`] },
  ];
  return (
    <article className="mx-auto max-w-2xl px-5 py-16">
      <h1 className="text-[32px] leading-[1.15] font-bold tracking-[-0.025em] text-text-primary">Confidentialité et données</h1>
      <p className="mt-4 text-[15px] leading-7 text-text-secondary">Le patient voit sa pharmacie, pas un logiciel. Le pharmacien décide. Aucune donnée n&apos;est revendue. Voici, concrètement, ce que cela veut dire.</p>
      {blocks.map((block) => (
        <section key={block.t} id={block.id} className="mt-10 scroll-mt-24">
          <h2 className="text-[20px] font-semibold text-text-primary">{block.t}</h2>
          {block.p.map((paragraph) => (
            <p key={paragraph} className="mt-3 text-[14.5px] leading-7 text-text-secondary">{paragraph}</p>
          ))}
        </section>
      ))}
    </article>
  );
}
