import type { ProductCategoryCode } from "../../src/core/ai/types";

/**
 * CATALOGUE DE DÉMONSTRATION — produits, marques et prix ENTIÈREMENT FICTIFS.
 * Les marques citées sont inventées et ne désignent aucun produit réel.
 */

export type DemoProduct = {
  slug: string;
  name: string;
  brand: string;
  category: ProductCategoryCode;
  subCategory: string;
  ean: string;
  description: string;
  commercialClaims: string[];
  precautions: string[];
  matchingTags: string[];
  contraindications: string[];
  purchasePriceCents: number;
  salePriceCents: number;
  vatRate: number;
  quantity: number;
  alertThreshold: number;
  location: string;
};

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    slug: "probio-flore-10",
    name: "Flore Équilibre 10 milliards",
    brand: "Vitalys",
    category: "PROBIOTIQUES",
    subCategory: "Ferments lactiques",
    ean: "3400900000011",
    description: "Gélules de ferments lactiques, 1 gélule par jour pendant 10 jours.",
    commercialClaims: ["Contribue à l'équilibre de la flore intestinale"],
    precautions: ["À prendre à distance de l'antibiotique (2 heures)."],
    matchingTags: ["probiotique", "flore", "intestinale", "tolérance", "digestive", "ferments"],
    contraindications: ["immunodépression"],
    purchasePriceCents: 620,
    salePriceCents: 1490,
    vatRate: 5.5,
    quantity: 34,
    alertThreshold: 8,
    location: "Linéaire A2",
  },
  {
    slug: "probio-confort",
    name: "Confort Intestinal 8 souches",
    brand: "Naturéo",
    category: "PROBIOTIQUES",
    subCategory: "Ferments lactiques",
    ean: "3400900000028",
    description: "Complément à base de 8 souches, cure de 30 jours.",
    commercialClaims: ["Soutient le confort digestif au quotidien"],
    precautions: ["Conserver au réfrigérateur après ouverture."],
    matchingTags: ["probiotique", "flore", "confort", "digestif", "intestinale"],
    contraindications: ["immunodépression"],
    purchasePriceCents: 890,
    salePriceCents: 2190,
    vatRate: 5.5,
    quantity: 21,
    alertThreshold: 6,
    location: "Linéaire A2",
  },
  {
    slug: "probio-enfant",
    name: "Flore Junior sachets",
    brand: "Vitalys",
    category: "PROBIOTIQUES",
    subCategory: "Pédiatrie",
    ean: "3400900000035",
    description: "Sachets à diluer, dès 3 ans.",
    commercialClaims: ["Formule adaptée aux enfants dès 3 ans"],
    precautions: ["Ne convient pas avant 3 ans."],
    matchingTags: ["probiotique", "flore", "enfant", "pédiatrique", "digestive"],
    contraindications: ["enfant de moins de 3 ans", "immunodépression"],
    purchasePriceCents: 540,
    salePriceCents: 1290,
    vatRate: 5.5,
    quantity: 12,
    alertThreshold: 5,
    location: "Linéaire A3",
  },
  {
    slug: "vitamine-d3-1000",
    name: "Vitamine D3 1000 UI",
    brand: "Solvia",
    category: "VITAMINES",
    subCategory: "Vitamine D",
    ean: "3400900000042",
    description: "Comprimés à croquer, 1 par jour.",
    commercialClaims: ["Contribue au maintien d'une ossature normale"],
    precautions: ["Ne pas cumuler avec une supplémentation prescrite."],
    matchingTags: ["vitamine", "vitamine d", "os", "ossature", "calcium", "immunité"],
    contraindications: [],
    purchasePriceCents: 310,
    salePriceCents: 890,
    vatRate: 5.5,
    quantity: 48,
    alertThreshold: 12,
    location: "Linéaire B1",
  },
  {
    slug: "vitamine-c-1000",
    name: "Vitamine C 1000 effervescent",
    brand: "Solvia",
    category: "VITAMINES",
    subCategory: "Vitamine C",
    ean: "3400900000059",
    description: "Comprimés effervescents goût orange, 20 unités.",
    commercialClaims: ["Contribue à réduire la fatigue"],
    precautions: ["Contient du sodium : prudence en cas de régime sans sel."],
    matchingTags: ["vitamine", "vitamine c", "fatigue", "immunité", "tonus"],
    contraindications: [],
    purchasePriceCents: 240,
    salePriceCents: 690,
    vatRate: 5.5,
    quantity: 62,
    alertThreshold: 15,
    location: "Linéaire B1",
  },
  {
    slug: "vitamine-b-complexe",
    name: "Complexe Vitamines B",
    brand: "Naturéo",
    category: "VITAMINES",
    subCategory: "Vitamines B",
    ean: "3400900000066",
    description: "Complexe B1 à B12, 60 comprimés.",
    commercialClaims: ["Contribue au fonctionnement normal du système nerveux"],
    precautions: [],
    matchingTags: ["vitamine", "vitamine b6", "fatigue", "nerveux", "tonus"],
    contraindications: [],
    purchasePriceCents: 420,
    salePriceCents: 1190,
    vatRate: 5.5,
    quantity: 27,
    alertThreshold: 8,
    location: "Linéaire B1",
  },
  {
    slug: "magnesium-marin-b6",
    name: "Magnésium Marin + B6",
    brand: "Solvia",
    category: "MAGNESIUM",
    subCategory: "Magnésium marin",
    ean: "3400900000073",
    description: "Gélules, cure de 30 jours.",
    commercialClaims: ["Contribue à réduire la fatigue et au fonctionnement musculaire normal"],
    precautions: ["Déconseillé en cas d'insuffisance rénale."],
    matchingTags: ["magnésium", "fatigue", "crampes", "vitamine b6", "musculaire", "nervosité"],
    contraindications: ["insuffisance rénale"],
    purchasePriceCents: 480,
    salePriceCents: 1390,
    vatRate: 5.5,
    quantity: 39,
    alertThreshold: 10,
    location: "Linéaire B2",
  },
  {
    slug: "magnesium-bisglycinate",
    name: "Magnésium Bisglycinate haute tolérance",
    brand: "Naturéo",
    category: "MAGNESIUM",
    subCategory: "Magnésium chélaté",
    ean: "3400900000080",
    description: "Forme chélatée, 90 gélules.",
    commercialClaims: ["Forme reconnue pour sa bonne tolérance digestive"],
    precautions: ["Déconseillé en cas d'insuffisance rénale."],
    matchingTags: ["magnésium", "fatigue", "crampes", "tolérance", "musculaire"],
    contraindications: ["insuffisance rénale"],
    purchasePriceCents: 760,
    salePriceCents: 1990,
    vatRate: 5.5,
    quantity: 18,
    alertThreshold: 6,
    location: "Linéaire B2",
  },
  {
    slug: "fer-bisglycinate",
    name: "Fer Bisglycinate 14 mg",
    brand: "Solvia",
    category: "MINERAUX",
    subCategory: "Fer",
    ean: "3400900000097",
    description: "Complément en fer, 60 gélules.",
    commercialClaims: ["Contribue à réduire la fatigue"],
    precautions: ["À distance du thé et du café."],
    matchingTags: ["fer", "fatigue", "minéral"],
    contraindications: [],
    purchasePriceCents: 520,
    salePriceCents: 1490,
    vatRate: 5.5,
    quantity: 15,
    alertThreshold: 6,
    location: "Linéaire B2",
  },
  {
    slug: "zinc-selenium",
    name: "Zinc + Sélénium",
    brand: "Naturéo",
    category: "MINERAUX",
    subCategory: "Oligo-éléments",
    ean: "3400900000103",
    description: "Oligo-éléments, 60 comprimés.",
    commercialClaims: ["Contribue au fonctionnement normal du système immunitaire"],
    precautions: [],
    matchingTags: ["zinc", "sélénium", "immunité", "minéral", "peau"],
    contraindications: [],
    purchasePriceCents: 390,
    salePriceCents: 1090,
    vatRate: 5.5,
    quantity: 24,
    alertThreshold: 8,
    location: "Linéaire B2",
  },
  {
    slug: "calcium-vitamine-d",
    name: "Calcium 500 + Vitamine D3",
    brand: "Solvia",
    category: "MINERAUX",
    subCategory: "Calcium",
    ean: "3400900000110",
    description: "Comprimés à croquer, 60 unités.",
    commercialClaims: ["Contribue au maintien d'une ossature normale"],
    precautions: ["À distance de certains traitements : demander conseil."],
    matchingTags: ["calcium", "vitamine d", "os", "ossature"],
    contraindications: ["insuffisance rénale"],
    purchasePriceCents: 450,
    salePriceCents: 1250,
    vatRate: 5.5,
    quantity: 9,
    alertThreshold: 10,
    location: "Linéaire B2",
  },
  {
    slug: "bain-bouche-doux",
    name: "Bain de bouche sans alcool",
    brand: "Oralis",
    category: "HYGIENE",
    subCategory: "Bucco-dentaire",
    ean: "3400900000127",
    description: "Flacon 500 ml, usage quotidien.",
    commercialClaims: ["Apaise et rafraîchit sans assécher"],
    precautions: [],
    matchingTags: ["bouche", "sèche", "salive", "hygiène", "bucco-dentaire", "buccale"],
    contraindications: [],
    purchasePriceCents: 280,
    salePriceCents: 790,
    vatRate: 20,
    quantity: 41,
    alertThreshold: 10,
    location: "Linéaire C1",
  },
  {
    slug: "spray-bouche-seche",
    name: "Spray bouche sèche",
    brand: "Oralis",
    category: "HYGIENE",
    subCategory: "Bucco-dentaire",
    ean: "3400900000134",
    description: "Spray 50 ml, jusqu'à 6 fois par jour.",
    commercialClaims: ["Hydrate durablement la muqueuse buccale"],
    precautions: [],
    matchingTags: ["bouche", "sèche", "salive", "hydratation", "buccale", "hygiène"],
    contraindications: [],
    purchasePriceCents: 420,
    salePriceCents: 1190,
    vatRate: 20,
    quantity: 16,
    alertThreshold: 6,
    location: "Linéaire C1",
  },
  {
    slug: "dentifrice-sensible",
    name: "Dentifrice dents sensibles",
    brand: "Oralis",
    category: "HYGIENE",
    subCategory: "Bucco-dentaire",
    ean: "3400900000141",
    description: "Tube 75 ml.",
    commercialClaims: ["Formulé pour les dents sensibles"],
    precautions: [],
    matchingTags: ["dents", "hygiène", "bucco-dentaire", "sensible"],
    contraindications: [],
    purchasePriceCents: 210,
    salePriceCents: 590,
    vatRate: 20,
    quantity: 55,
    alertThreshold: 12,
    location: "Linéaire C1",
  },
  {
    slug: "gel-hydroalcoolique",
    name: "Gel hydroalcoolique 100 ml",
    brand: "Puréa",
    category: "HYGIENE",
    subCategory: "Antisepsie des mains",
    ean: "3400900000158",
    description: "Format poche.",
    commercialClaims: ["Format nomade"],
    precautions: ["Usage externe. Tenir hors de portée des enfants."],
    matchingTags: ["mains", "hygiène", "gel"],
    contraindications: ["enfant"],
    purchasePriceCents: 90,
    salePriceCents: 290,
    vatRate: 20,
    quantity: 78,
    alertThreshold: 20,
    location: "Comptoir",
  },
  {
    slug: "creme-emolliente",
    name: "Crème émolliente peaux très sèches",
    brand: "Dermalia",
    category: "DERMOCOSMETIQUE",
    subCategory: "Émollients",
    ean: "3400900000165",
    description: "Tube 400 ml, sans parfum.",
    commercialClaims: ["Nourrit intensément et apaise les tiraillements"],
    precautions: ["Éviter l'application sur plaie ouverte."],
    matchingTags: [
      "hydratation",
      "émollient",
      "peau",
      "sensible",
      "apaisant",
      "sécheresse",
      "cutanée",
    ],
    contraindications: [],
    purchasePriceCents: 640,
    salePriceCents: 1690,
    vatRate: 20,
    quantity: 29,
    alertThreshold: 8,
    location: "Linéaire D1",
  },
  {
    slug: "baume-reparateur",
    name: "Baume réparateur zones fragilisées",
    brand: "Dermalia",
    category: "DERMOCOSMETIQUE",
    subCategory: "Réparateurs",
    ean: "3400900000172",
    description: "Tube 100 ml, sans parfum.",
    commercialClaims: ["Aide la peau à retrouver son confort"],
    precautions: ["Éviter le contour des yeux."],
    matchingTags: ["réparateur", "apaisant", "peau", "sensible", "hydratation", "cutanée"],
    contraindications: [],
    purchasePriceCents: 520,
    salePriceCents: 1390,
    vatRate: 20,
    quantity: 22,
    alertThreshold: 8,
    location: "Linéaire D1",
  },
  {
    slug: "spf50-visage",
    name: "Fluide solaire visage SPF 50+",
    brand: "Solaris",
    category: "DERMOCOSMETIQUE",
    subCategory: "Photoprotection",
    ean: "3400900000189",
    description: "Fluide 50 ml, très haute protection.",
    commercialClaims: ["Très haute protection UVA/UVB"],
    precautions: ["Renouveler l'application toutes les 2 heures."],
    matchingTags: ["protection", "solaire", "spf", "photoprotection", "visage", "uv"],
    contraindications: [],
    purchasePriceCents: 780,
    salePriceCents: 1990,
    vatRate: 20,
    quantity: 33,
    alertThreshold: 10,
    location: "Linéaire D2",
  },
  {
    slug: "spf50-corps",
    name: "Lait solaire corps SPF 50+",
    brand: "Solaris",
    category: "DERMOCOSMETIQUE",
    subCategory: "Photoprotection",
    ean: "3400900000196",
    description: "Lait 200 ml, très haute protection.",
    commercialClaims: ["Très haute protection pour le corps"],
    precautions: ["Renouveler après la baignade."],
    matchingTags: ["protection", "solaire", "spf", "photoprotection", "corps", "uv"],
    contraindications: [],
    purchasePriceCents: 890,
    salePriceCents: 2190,
    vatRate: 20,
    quantity: 4,
    alertThreshold: 8,
    location: "Linéaire D2",
  },
  {
    slug: "stick-levres-spf",
    name: "Stick lèvres SPF 30",
    brand: "Solaris",
    category: "DERMOCOSMETIQUE",
    subCategory: "Photoprotection",
    ean: "3400900000202",
    description: "Stick 4 g.",
    commercialClaims: ["Protège et nourrit les lèvres"],
    precautions: [],
    matchingTags: ["protection", "solaire", "spf", "lèvres", "photoprotection"],
    contraindications: [],
    purchasePriceCents: 190,
    salePriceCents: 590,
    vatRate: 20,
    quantity: 47,
    alertThreshold: 12,
    location: "Comptoir",
  },
  {
    slug: "cold-cream",
    name: "Cold cream protecteur",
    brand: "Dermalia",
    category: "DERMATOLOGIE",
    subCategory: "Protecteurs cutanés",
    ean: "3400900000219",
    description: "Pot 100 ml.",
    commercialClaims: ["Protège les peaux exposées au froid"],
    precautions: [],
    matchingTags: ["peau", "protection", "hydratation", "sécheresse"],
    contraindications: [],
    purchasePriceCents: 380,
    salePriceCents: 1090,
    vatRate: 20,
    quantity: 19,
    alertThreshold: 6,
    location: "Linéaire D1",
  },
  {
    slug: "gel-apaisant-peau",
    name: "Gel apaisant après-soleil",
    brand: "Solaris",
    category: "DERMATOLOGIE",
    subCategory: "Apaisants",
    ean: "3400900000226",
    description: "Gel 200 ml.",
    commercialClaims: ["Apaise immédiatement les peaux échauffées"],
    precautions: [],
    matchingTags: ["apaisant", "peau", "après-soleil", "hydratation"],
    contraindications: [],
    purchasePriceCents: 330,
    salePriceCents: 990,
    vatRate: 20,
    quantity: 26,
    alertThreshold: 8,
    location: "Linéaire D2",
  },
  {
    slug: "pansement-hydrocolloide",
    name: "Pansements hydrocolloïdes x10",
    brand: "Medipro",
    category: "DISPOSITIFS_MEDICAUX",
    subCategory: "Pansements",
    ean: "3400900000233",
    description: "Boîte de 10 pansements.",
    commercialClaims: ["Favorise la cicatrisation en milieu humide"],
    precautions: ["Ne pas utiliser sur une plaie infectée."],
    matchingTags: ["pansement", "plaie", "cicatrisation"],
    contraindications: [],
    purchasePriceCents: 310,
    salePriceCents: 890,
    vatRate: 5.5,
    quantity: 31,
    alertThreshold: 10,
    location: "Tiroir E1",
  },
  {
    slug: "thermometre-frontal",
    name: "Thermomètre frontal sans contact",
    brand: "Medipro",
    category: "DISPOSITIFS_MEDICAUX",
    subCategory: "Mesure",
    ean: "3400900000240",
    description: "Mesure en 1 seconde, mémoire 30 relevés.",
    commercialClaims: ["Mesure rapide sans contact"],
    precautions: [],
    matchingTags: ["thermomètre", "fièvre", "mesure"],
    contraindications: [],
    purchasePriceCents: 1450,
    salePriceCents: 3490,
    vatRate: 20,
    quantity: 7,
    alertThreshold: 3,
    location: "Vitrine",
  },
  {
    slug: "compresses-steriles",
    name: "Compresses stériles 10 x 10 cm",
    brand: "Medipro",
    category: "DISPOSITIFS_MEDICAUX",
    subCategory: "Pansements",
    ean: "3400900000257",
    description: "Boîte de 20 sachets.",
    commercialClaims: ["Compresses stériles à usage unique"],
    precautions: [],
    matchingTags: ["compresse", "plaie", "stérile"],
    contraindications: [],
    purchasePriceCents: 180,
    salePriceCents: 490,
    vatRate: 5.5,
    quantity: 44,
    alertThreshold: 12,
    location: "Tiroir E1",
  },
  {
    slug: "fibres-transit",
    name: "Fibres douces transit",
    brand: "Naturéo",
    category: "NUTRITION",
    subCategory: "Transit",
    ean: "3400900000264",
    description: "Poudre à diluer, 30 doses.",
    commercialClaims: ["Contribue à un transit régulier"],
    precautions: ["Boire abondamment pendant la cure."],
    matchingTags: ["transit", "fibres", "confort", "digestif", "constipation"],
    contraindications: [],
    purchasePriceCents: 490,
    salePriceCents: 1290,
    vatRate: 5.5,
    quantity: 23,
    alertThreshold: 8,
    location: "Linéaire A3",
  },
  {
    slug: "solution-rehydratation",
    name: "Solution de réhydratation orale",
    brand: "Vitalys",
    category: "NUTRITION",
    subCategory: "Réhydratation",
    ean: "3400900000271",
    description: "10 sachets, dès 12 mois.",
    commercialClaims: ["Compense les pertes en eau et en sels minéraux"],
    precautions: ["Consulter en cas de diarrhée persistante."],
    matchingTags: ["réhydratation", "diarrhée", "digestif", "sels minéraux"],
    contraindications: [],
    purchasePriceCents: 340,
    salePriceCents: 890,
    vatRate: 5.5,
    quantity: 17,
    alertThreshold: 6,
    location: "Linéaire A3",
  },
  {
    slug: "complement-proteine",
    name: "Complément nutritionnel vanille",
    brand: "Vitalys",
    category: "NUTRITION",
    subCategory: "Nutrition clinique",
    ean: "3400900000288",
    description: "4 bouteilles de 200 ml.",
    commercialClaims: ["Apport énergétique et protéique concentré"],
    precautions: ["Sur conseil du professionnel de santé."],
    matchingTags: ["nutrition", "protéine", "dénutrition", "énergie"],
    contraindications: [],
    purchasePriceCents: 720,
    salePriceCents: 1790,
    vatRate: 5.5,
    quantity: 11,
    alertThreshold: 5,
    location: "Réserve",
  },
  {
    slug: "argile-gastrique",
    name: "Confort gastrique argile & réglisse",
    brand: "Naturéo",
    category: "SOINS",
    subCategory: "Confort digestif",
    ean: "3400900000295",
    description: "20 sachets à diluer.",
    commercialClaims: ["Aide à retrouver un confort gastrique"],
    precautions: ["À distance des autres traitements (2 heures)."],
    matchingTags: ["confort", "gastrique", "estomac", "digestion", "digestif"],
    contraindications: ["grossesse"],
    purchasePriceCents: 410,
    salePriceCents: 1090,
    vatRate: 5.5,
    quantity: 25,
    alertThreshold: 8,
    location: "Linéaire A1",
  },
  {
    slug: "pastilles-gorge",
    name: "Pastilles gorge miel-citron",
    brand: "Naturéo",
    category: "SOINS",
    subCategory: "ORL",
    ean: "3400900000301",
    description: "Boîte de 24 pastilles.",
    commercialClaims: ["Adoucit la gorge irritée"],
    precautions: [],
    matchingTags: ["gorge", "irritation", "orl"],
    contraindications: [],
    purchasePriceCents: 190,
    salePriceCents: 590,
    vatRate: 5.5,
    quantity: 58,
    alertThreshold: 15,
    location: "Comptoir",
  },
  {
    slug: "spray-nasal-marin",
    name: "Spray nasal eau de mer isotonique",
    brand: "Puréa",
    category: "SOINS",
    subCategory: "ORL",
    ean: "3400900000318",
    description: "Flacon 100 ml.",
    commercialClaims: ["Nettoie et dégage le nez en douceur"],
    precautions: [],
    matchingTags: ["nez", "nasal", "orl", "hygiène"],
    contraindications: [],
    purchasePriceCents: 230,
    salePriceCents: 690,
    vatRate: 5.5,
    quantity: 36,
    alertThreshold: 10,
    location: "Linéaire A1",
  },
  {
    slug: "valeriane-sommeil",
    name: "Valériane & Mélisse sommeil",
    brand: "Naturéo",
    category: "PHYTOTHERAPIE",
    subCategory: "Sommeil",
    ean: "3400900000325",
    description: "30 comprimés.",
    commercialClaims: ["Contribue à un sommeil de qualité"],
    precautions: ["Déconseillé pendant la grossesse et l'allaitement."],
    matchingTags: ["sommeil", "détente", "plante", "nervosité"],
    contraindications: ["grossesse", "allaitement"],
    purchasePriceCents: 360,
    salePriceCents: 1090,
    vatRate: 5.5,
    quantity: 20,
    alertThreshold: 7,
    location: "Linéaire B3",
  },
  {
    slug: "gingembre-nausees",
    name: "Gingembre bio confort digestif",
    brand: "Naturéo",
    category: "PHYTOTHERAPIE",
    subCategory: "Digestion",
    ean: "3400900000332",
    description: "60 gélules bio.",
    commercialClaims: ["Contribue au confort digestif"],
    precautions: ["Demander conseil en cas de traitement anticoagulant."],
    matchingTags: ["digestion", "nausées", "plante", "digestif", "confort"],
    contraindications: ["grossesse"],
    purchasePriceCents: 320,
    salePriceCents: 990,
    vatRate: 5.5,
    quantity: 14,
    alertThreshold: 6,
    location: "Linéaire B3",
  },
  {
    slug: "echinacea-immunite",
    name: "Échinacée défenses naturelles",
    brand: "Naturéo",
    category: "PHYTOTHERAPIE",
    subCategory: "Immunité",
    ean: "3400900000349",
    description: "45 gélules.",
    commercialClaims: ["Soutient les défenses naturelles"],
    precautions: ["Déconseillé en cas de maladie auto-immune."],
    matchingTags: ["immunité", "défenses", "plante", "hiver"],
    contraindications: ["immunodépression", "grossesse"],
    purchasePriceCents: 380,
    salePriceCents: 1190,
    vatRate: 5.5,
    quantity: 0,
    alertThreshold: 6,
    location: "Linéaire B3",
  },
  {
    slug: "spray-anti-moustique",
    name: "Spray répulsif moustiques",
    brand: "Puréa",
    category: "SAISONNIER",
    subCategory: "Été",
    ean: "3400900000356",
    description: "Flacon 100 ml, zones tempérées.",
    commercialClaims: ["Protection jusqu'à 6 heures"],
    precautions: ["Ne pas appliquer sur le visage des enfants."],
    matchingTags: ["moustique", "répulsif", "été"],
    contraindications: ["enfant"],
    purchasePriceCents: 410,
    salePriceCents: 1190,
    vatRate: 20,
    quantity: 13,
    alertThreshold: 5,
    location: "Tête de gondole",
  },
  {
    slug: "brumisateur",
    name: "Brumisateur eau thermale 150 ml",
    brand: "Puréa",
    category: "SAISONNIER",
    subCategory: "Été",
    ean: "3400900000363",
    description: "Spray 150 ml.",
    commercialClaims: ["Rafraîchit et apaise instantanément"],
    precautions: [],
    matchingTags: ["apaisant", "peau", "rafraîchissant", "été"],
    contraindications: [],
    purchasePriceCents: 260,
    salePriceCents: 790,
    vatRate: 20,
    quantity: 30,
    alertThreshold: 8,
    location: "Tête de gondole",
  },
];
