import "server-only";
import { prisma } from "@/server/db/client";
import { getRequestMeta } from "@/server/http/request-meta";

/**
 * Journal d'audit.
 *
 * Règle absolue : `metadata` ne contient jamais de donnée de santé en clair.
 * On y consigne des identifiants, des compteurs et des libellés d'action, pas
 * le contenu d'une ordonnance ni le profil médical d'un patient.
 */
export type AuditAction =
  | "auth.login"
  | "auth.login_failed"
  | "auth.logout"
  | "auth.password_link_sent"
  | "auth.password_set"
  | "auth.password_changed"
  | "auth.pharmacy_switched"
  | "patient.created"
  | "patient.updated"
  | "patient.deleted"
  | "patient.health_viewed"
  | "patient.health_updated"
  | "patient.consent_updated"
  | "product.created"
  | "product.updated"
  | "product.deleted"
  | "product.imported"
  | "pharmacy.updated"
  | "stock.connection_pairing_issued"
  | "stock.connection_paired"
  | "stock.connection_revoked"
  | "stock.connection_settings_changed"
  | "robot.setup_saved"
  | "robot.setup_cleared"
  | "robot.technical_saved"
  | "stock.agent_sync"
  | "pharmacy.onboarding_completed"
  | "stock.adjusted"
  | "drug_stock.adjusted"
  | "drug_stock.removed"
  | "drug_stock.imported"
  | "prescription.created"
  | "prescription.verified"
  | "prescription.patient_attached"
  | "prescription.regulation_checked"
  | "prescription.counter_scan"
  | "prescription.counter_reset"
  | "pharmacy.install_guide_sent"
  | "prescription.file_erased"
  | "patient_data.purged"
  | "counter.request_advised"
  | "stock.post_export_path_set"
  | "stock.post_sync_requested"
  | "prescription.barcode_learned"
  | "stock.post_pairing_created"
  | "stock.post_paired"
  | "stock.post_revoked"
  | "billing.invite_sent"
  | "billing.cancel_scheduled"
  | "billing.cancel_revoked"
  | "billing.access_suspended"
  | "billing.access_restored"
  | "billing.plan_saved"
  | "billing.portal_opened"
  | "billing.contract_prepared"
  | "prescription.regulation_unchecked"
  | "prescription.line_identified"
  | "prescription.analyzed"
  | "prescription.safety_acknowledged"
  | "prescription.validated"
  | "prescription.deleted"
  | "recommendation.accepted"
  | "recommendation.modified"
  | "recommendation.replaced"
  | "recommendation.removed"
  | "recommendation.added_manually"
  | "recommendation.presented"
  | "recommendation.declined"
  | "recommendation.reopened"
  | "opportunity.answered"
  | "team.member_created"
  | "team.invitation_sent"
  | "team.invitation_resent"
  | "team.invitation_revoked"
  | "team.invitation_accepted"
  | "team.join_requested"
  | "team.join_approved"
  | "team.join_refused"
  | "team.member_enabled"
  | "team.member_disabled"
  | "team.member_role_changed"
  | "team.member_updated"
  | "team.member_reordered"
  | "team.principal_changed"
  | "team.member_password_reset"
  | "platform.pharmacy_created"
  | "platform.pharmacy_updated"
  | "platform.pharmacy_status_changed"
  | "platform.owner_created"
  | "platform.member_access_resent"
  | "platform.member_access_changed"
  | "platform.member_deleted"
  | "platform.member_removed"
  | "platform.user_deleted"
  | "platform.pharmacy_deleted"
  | "platform.support_replied"
  | "platform.support_status_changed"
  | "platform.invitation_sent"
  | "platform.invitation_link_issued"
  | "platform.invitation_email_changed"
  | "platform.invitation_revoked"
  | "platform.pharmacy_email_changed"
  | "platform.owner_email_changed"
  | "platform.owner_welcome_resent"
  | "platform.post_count_changed"
  | "onboarding.opened"
  | "onboarding.completed"
  | "platform.admin_created"
  | "platform.admin_link_resent"
  | "platform.admin_activated"
  | "platform.admin_deactivated"
  | "platform.admin_deleted"
  | "rule.created"
  | "association.created"
  | "association.updated"
  | "association.deleted"
  | "counter_post.assigned"
  | "counter_post.claimed"
  | "counter_post.released"
  | "counter_post.renamed"
  | "knowledge.gap_answered"
  | "knowledge.gap_dismissed"
  | "knowledge.document_deposited"
  | "knowledge.document_analysed"
  | "knowledge.proposal_decided"
  | "knowledge.document_deleted"
  | "counter_window.advice_decided"
  | "counter_window.email_saved"
  | "counter_window.sale_finished"
  | "counter_window.patient_report_sent"
  | "counter_window.monthly_report_sent"
  | "central_advice.rule_decided"
  | "central_advice.rule_created"
  | "central_advice.association_created"
  | "central_advice.association_decided"
  | "rule.deleted"
  | "document.generated"
  | "document.delivered"
  | "document.viewed"
  | "reminder.scheduled"
  | "reminder.sent"
  | "reminder.snoozed"
  | "reminder.cancelled"
  | "reminder.opted_out"
  | "reminder.answered"
  | "reminder.handled"
  | "sale.created"
  | "team.member_invited"
  | "team.member_updated"
  | "team.member_disabled"
  | "settings.updated"
  | "sales.rep_created"
  | "sales.rep_updated"
  | "sales.rep_invited"
  | "sales.prospect_created"
  | "sales.prospect_updated"
  | "sales.prospect_status_changed"
  | "sales.prospect_reassigned"
  | "sales.prospect_blocked"
  | "sales.contract_generated"
  | "sales.contract_sent"
  | "sales.contract_signature_recorded"
  | "sales.contract_event"
  | "sales.pharmacy_created"
  | "sales.commission_updated"
  | "sales.company_profile_updated"
  | "sales.signature_webhook"
  | "sales.contract_reminder"
  | "sales.subscription_requested"
  | "platform.setting_updated"
  | "range.saved"
  | "range.deleted"
  | "challenge.saved"
  | "challenge.deleted"
  | "challenge.entry_added"
  | "challenge.entry_deleted"
  | "stock.lot_saved"
  | "stock.lot_resolved"
  | "stock.lot_deleted"
  | "stock.short_date_settings_updated"
  | "vigilance.product_saved"
  | "vigilance.product_deleted"
  | "recommendation.validation_required"
  | "training.saved"
  | "training.archived"
  | "training.progress_updated"
  | "partner.application_received"
  | "partner.application_status_changed"
  | "partner.application_note_added"
  | "partner.saved"
  | "partner.status_changed"
  | "partner.contact_saved"
  | "partner.contact_deleted"
  | "partner.contract_saved"
  | "partner.integration_saved"
  | "partner.brand_saved"
  | "partner.brand_status_changed"
  | "partner.brand_audience_updated"
  | "partner.pilot_updated"
  | "partner.range_saved"
  | "partner.product_saved"
  | "partner.product_deleted"
  | "partner.document_saved"
  | "partner.offer_saved"
  | "partner.preference_updated"
  | "partner.lead_created"
  | "partner.order_created"
  | "partner.order_status_changed"
  | "partner.orders_exported"
  // Centre de contrôle Super Admin
  | "billing.contract_price_changed"
  | "billing.subscription_refreshed"
  | "billing.cancellation_created"
  | "billing.cancellation_status_changed"
  | "billing.cancellation_note_added"
  | "billing.cancellation_stripe_scheduled"
  | "platform.note_added"
  | "platform.note_pinned"
  | "platform.email_sent"
  | "platform.email_test_sent"
  | "platform.email_template_saved"
  | "platform.email_template_reset"
  | "platform.automation_updated"
  | "platform.automation_run"
  | "platform.incident_resolved"
  | "sales.contract_reminded"
  | "sales.demo_scheduled"
  | "sales.demo_done"
  | "sales.demo_canceled"
  | "sales.followup_set"
  | "campaign.created"
  | "campaign.updated"
  | "campaign.test_sent"
  | "campaign.scheduled"
  | "campaign.sent"
  | "campaign.resumed"
  | "campaign.canceled"
  | "campaign.deleted"
  | "campaign.referral_offer_started"
  | "campaign.referral_offer_ended"
  | "marketing.opted_out"
  | "marketing.opt_out_removed"
  | "patient_news.subscribed"
  | "patient_news.unsubscribed"
  | "patient_news.announcement_sent"
  | "patient_news.settings_changed"
  | "patient_news.purged"
  | "referral.filleul_notified"
  | "referral.lead_proposed"
  | "referral.lead_linked"
  | "referral.lead_status_changed"
  | "partner.invitation_sent"
  | "platform.standard_commission_updated"
  | "platform.public_offer_published"
  | "sales_application.created"
  | "sales_application.status_changed"
  | "sales_application.note_added"
  | "sales_application.converted"
  | "sales_application.cv_downloaded"
  | "assortment.lab_suggested"
  | "demo.delivery_simulated"
  | "demo.reset"
  // Dépôts de stock : le fichier de stock du titulaire (jamais son contenu)
  | "stock.deposit_received"
  | "stock.deposit_applied"
  | "stock.deposit_held"
  | "stock.deposit_failed"
  | "stock.deposit_decided"
  | "stock.deposit_retried"
  | "stock.deposit_files_purged"
  | "stock.deposit_downloaded"
  | "sales.director_created"
  | "sales.director_updated"
  | "sales.director_invited"
  | "sales.director_deleted"
  | "sales.rep_deleted"
  | "sales.invoice_created"
  | "sales.invoice_updated"
  | "sales.invoice_deleted"
  | "sales.challenge_saved"
  | "sales.challenge_deleted";

export async function recordAudit(params: {
  action: AuditAction;
  entityType: string;
  entityId?: string | null;
  pharmacyId?: string | null;
  userId?: string | null;
  platformAdminId?: string | null;
  /** Commercial à l'origine de l'action, pour l'extranet. */
  salesRepId?: string | null;
  /** Directeur commercial à l'origine de l'action, pour son espace. */
  salesDirectorId?: string | null;
  metadata?: Record<string, unknown>;
}): Promise<void> {
  try {
    const meta = await getRequestMeta();

    await prisma.auditLog.create({
      data: {
        action: params.action,
        entityType: params.entityType,
        entityId: params.entityId ?? null,
        pharmacyId: params.pharmacyId ?? null,
        userId: params.userId ?? null,
        platformAdminId: params.platformAdminId ?? null,
        metadata: ({ ...(params.metadata ?? {}), ...(params.salesRepId ? { salesRepId: params.salesRepId } : {}), ...(params.salesDirectorId ? { salesDirectorId: params.salesDirectorId } : {}) }) as never,
        ipAddress: meta.ipAddress,
        userAgent: meta.userAgent,
      },
    });
  } catch (error) {
    // L'audit ne doit jamais faire échouer l'action métier ; on trace côté
    // serveur pour ne pas perdre l'information silencieusement.
    console.error("[audit] écriture impossible", params.action, error);
  }
}
